name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Code Lint
        run: pnpm run lint

      - name: Type Check
        run: pnpm run type:check

      - name: Run Component Testing
        run: pnpm run test:component

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: pnpm run build
          start: pnpm run preview
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
