name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  install-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pnpm Setup
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm run format

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm vue-tsc --noEmit

  tests-cypress:
    runs-on: ubuntu-latest
    needs: install-lint
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pnpm Setup
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Restore cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          build: pnpm run build
          start: pnpm run preview
          record: true
          parallel: true
          group: 'E2E Tests'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Component Testing
        uses: cypress-io/github-action@v5
        with:
          install: false
          component: true
          record: true
          parallel: true
          group: 'Component Tests'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
