name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Pnpm Setup
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      - name: Code Lint
        run: pnpm run lint

      - name: Type Check
        run: pnpm run type:check

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          build: pnpm run build
          start: pnpm run preview
          record: true
          group: "E2E Tests"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Component Testing
        uses: cypress-io/github-action@v5
        with:
          install: false
          component: true
          record: true
          group: "Component Tests"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
